### ISSUE TITLE
Error during parsing Python3.g4

### ISSUE THREAD

**Issue by iljabauer** [premun/ingrid#1]
If I try to import the python 3 error following error occur:
There was an error during grammar parsing:
couldn't resolve rule "INDENT" (inside suite)

Can I somehow provide more information about the error?

**Comment by premun** [comment]
This means, that inside the rule called `suite` there is a reference to lexer rule `INDENT`, which is not present in the grammar.

You can manually add the `INDENT` rule or remove it from `suite`.

I am not sure whether it is some special name that ANTLR recognizes by default or whether the grammar is faulty.
