### ISSUE TITLE
Migrate to MPS 2018.3?

### ISSUE THREAD

**Issue by eugenschindler** [premun/ingrid#4]
It is not clear which MPS version this codebase is currently working on. Would it be possible to migrate this to MPS 2018.3?

**Comment by premun** [comment]
> It is not clear which MPS version this codebase is currently working on.

The requirements in the README state that it was developed for MPS 2017.1

> Would it be possible to migrate this to MPS 2018.3?

I am currently not maintaining this project anymore and don't have the environment set up. There was a continuation of this project from other students / JetBrains. Please check the forks of this repository.
